name: aqi_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.7.0
  envied: ^1.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  intl: ^0.20.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.3
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  envied_generator: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/videos/good_aqi_day_bg.mp4
    - assets/videos/bad_aqi_day_bg.mp4    
    - assets/videos/good_aqi_night_bg.mp4
    - assets/videos/bad_aqi_night_bg.mp4    